[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ferminet"
version = "0.2"
description = "A library to train networks to represent ground-state wavefunctions of fermionic systems"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "Apache-2.0" }
authors = [
    { name = "DeepMind" },
]
dependencies = [
    'absl-py',
    'attrs',
    'chex',
    'h5py',
    'folx @ git+https://github.com/microsoft/folx',
    'jax',
    'jaxlib',
    # TODO(b/230487443) - use released version of kfac.
    'kfac_jax @ git+https://github.com/deepmind/kfac-jax',
    'ml-collections',
    'optax',
    'numpy',
    'pandas',
    'pyscf',
    'pyblock',
    'scipy',
    'typing_extensions',
]

[project.optional-dependencies]
testing = [
    'flake8',
    'pylint',
    'pytest',
    'pytype',
]

[project.scripts]
ferminet = "ferminet.main:main_wrapper"

[project.urls]
Homepage = "https://github.com/ovo-Tim/ferminet"
Repository = "https://github.com/ovo-Tim/ferminet"

[tool.setuptools.packages.find]
include = ["ferminet*"]
